export const HELLO_SCENE_ID = 'HELLO_SCENE_ID';
export const BOT_NAME = 'ITMO_SANTA_BOT';
export const REST_API_URL = process.env.REST_API;

export const REGISTRATION_SCENE = 'REGISTRATION_SCENE';
export const USER_PROFILE_SCENE = 'USER_PROFILE_SCENE';
export const RECEIVER_ATTACHED_SCENE = 'RECEIVER_ATTACHED_SCENE';
export const GIFT_DELIVERED_SCENE = 'GIFT_DELIVERED_SCENE';
export const FINAL_SCENE = 'FINAL_SCENE';

//input
export const BIO_SCENE = 'BIO_SCENE';
export const LETTER_SCENE = 'LETTER_SCENE';
